from typing import Dict, Any

# dahili tema kataloğu. her tema standart 16 ANSI rengi + background/foreground/
# cursor/selection tutuyor; is_gradient olanlarda ayrica gradient_stops var.
# yeni tema eklerken tum anahtarlari doldurmak sart degil, adapterlerde
# .get() ile fallback var ama eksik birakmak renk tutarsizligi yaratiyor
BUILTIN_THEMES: Dict[str, Dict[str, Any]] = {
    "cyber-gradient": {
        "name": "Cyber Neon Gradient",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#00ffff", "#00d4ff", "#0099ff", "#6600ff", "#a800ff", "#ff00cc"],
        "background": "#08090f",
        "foreground": "#00ffff",
        "cursor": "#ff00cc",
        "selection": "#1a0933",
        "black": "#0c0d14",
        "red": "#ff0055",
        "green": "#00ff99",
        "yellow": "#ffcc00",
        "blue": "#0099ff",
        "magenta": "#a800ff",
        "cyan": "#00ffff",
        "white": "#e6f0ff",
        "brightBlack": "#3d3f58",
        "brightRed": "#ff3377",
        "brightGreen": "#33ffaa",
        "brightYellow": "#ffdd33",
        "brightBlue": "#33adff",
        "brightMagenta": "#c233ff",
        "brightCyan": "#33ffff",
        "brightWhite": "#ffffff",
    },
    "sunset-gradient": {
        "name": "Sunset Horizon Gradient",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#ff0055", "#ff5500", "#ff8800", "#ffaa00", "#ffd500"],
        "background": "#140a0f",
        "foreground": "#ffd500",
        "cursor": "#ff5500",
        "selection": "#33111f",
        "black": "#1a0d14",
        "red": "#ff0055",
        "green": "#ff8800",
        "yellow": "#ffd500",
        "blue": "#ff5577",
        "magenta": "#cc0066",
        "cyan": "#ffaa55",
        "white": "#fff0e6",
        "brightBlack": "#592b3a",
        "brightRed": "#ff3377",
        "brightGreen": "#ffa333",
        "brightYellow": "#ffdf33",
        "brightBlue": "#ff7799",
        "brightMagenta": "#e60073",
        "brightCyan": "#ffbb77",
        "brightWhite": "#ffffff",
    },
    "matrix-gradient": {
        "name": "Matrix Cyber Gradient",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#003300", "#008822", "#00cc44", "#00ff66", "#99ffcc"],
        "background": "#050d08",
        "foreground": "#00ff66",
        "cursor": "#99ffcc",
        "selection": "#0a2612",
        "black": "#07140b",
        "red": "#00aa33",
        "green": "#00ff66",
        "yellow": "#88ff00",
        "blue": "#00cc88",
        "magenta": "#00ffaa",
        "cyan": "#99ffcc",
        "white": "#e6fff0",
        "brightBlack": "#205933",
        "brightRed": "#33bb55",
        "brightGreen": "#33ff88",
        "brightYellow": "#a3ff33",
        "brightBlue": "#33dda3",
        "brightMagenta": "#33ffbb",
        "brightCyan": "#b3ffd9",
        "brightWhite": "#ffffff",
    },
    "aurora-gradient": {
        "name": "Aurora Borealis Gradient",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#00f0ff", "#5b86e5", "#8a2387", "#e94057", "#f27121"],
        "background": "#080c14",
        "foreground": "#00f0ff",
        "cursor": "#e94057",
        "selection": "#1a1b33",
        "black": "#0d1421",
        "red": "#e94057",
        "green": "#00f0ff",
        "yellow": "#f27121",
        "blue": "#5b86e5",
        "magenta": "#8a2387",
        "cyan": "#00f0ff",
        "white": "#e6f7ff",
        "brightBlack": "#3d4b66",
        "brightRed": "#ed6679",
        "brightGreen": "#33f3ff",
        "brightYellow": "#f58d4d",
        "brightBlue": "#7c9ee9",
        "brightMagenta": "#a13c9e",
        "brightCyan": "#33f3ff",
        "brightWhite": "#ffffff",
    },
    "synthwave-gradient": {
        "name": "Synthwave Laser Gradient",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#ff007f", "#ff00cc", "#9900ff", "#00ccff", "#00ffff"],
        "background": "#12081a",
        "foreground": "#ff00cc",
        "cursor": "#00ffff",
        "selection": "#2d0f3d",
        "black": "#180c24",
        "red": "#ff007f",
        "green": "#00ffcc",
        "yellow": "#ff00cc",
        "blue": "#00ccff",
        "magenta": "#9900ff",
        "cyan": "#00ffff",
        "white": "#ffe6f7",
        "brightBlack": "#552b73",
        "brightRed": "#ff3399",
        "brightGreen": "#33ffd6",
        "brightYellow": "#ff33d6",
        "brightBlue": "#33d6ff",
        "brightMagenta": "#ad33ff",
        "brightCyan": "#33ffff",
        "brightWhite": "#ffffff",
    },
    "fire-ice-gradient": {
        "name": "Fire & Ice Gradient",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#00f5d4", "#00bbf9", "#fee440", "#f15bb5", "#9b5de5"],
        "background": "#080b12",
        "foreground": "#00f5d4",
        "cursor": "#fee440",
        "selection": "#1a1e2e",
        "black": "#0e131f",
        "red": "#f15bb5",
        "green": "#00f5d4",
        "yellow": "#fee440",
        "blue": "#00bbf9",
        "magenta": "#9b5de5",
        "cyan": "#00f5d4",
        "white": "#e6fdff",
        "brightBlack": "#3d4b66",
        "brightRed": "#f47cc4",
        "brightGreen": "#33f7dd",
        "brightYellow": "#fee966",
        "brightBlue": "#33c9fa",
        "brightMagenta": "#af7dea",
        "brightCyan": "#33f7dd",
        "brightWhite": "#ffffff",
    },
    "deep-space-gradient": {
        "name": "Deep Space Nebula",
        "author": "TermCraft",
        "is_gradient": True,
        "gradient_stops": ["#0b0c10", "#1f2833", "#45a29e", "#66fcf1", "#c5c6c7"],
        "background": "#0b0c10",
        "foreground": "#66fcf1",
        "cursor": "#45a29e",
        "selection": "#1f2833",
        "black": "#12141a",
        "red": "#e056fd",
        "green": "#66fcf1",
        "yellow": "#f9ca24",
        "blue": "#45a29e",
        "magenta": "#be2edd",
        "cyan": "#66fcf1",
        "white": "#c5c6c7",
        "brightBlack": "#3a404d",
        "brightRed": "#e678fd",
        "brightGreen": "#85fdf4",
        "brightYellow": "#fad550",
        "brightBlue": "#6ab5b1",
        "brightMagenta": "#cb58e4",
        "brightCyan": "#85fdf4",
        "brightWhite": "#ffffff",
    },
    "tokyo-night": {
        "name": "Tokyo Night",
        "author": "folke",
        "background": "#1a1b26",
        "foreground": "#c0caf5",
        "cursor": "#c0caf5",
        "selection": "#33467c",
        "black": "#15161e",
        "red": "#f7768e",
        "green": "#9ece6a",
        "yellow": "#e0af68",
        "blue": "#7aa2f7",
        "magenta": "#bb9af7",
        "cyan": "#7dcfff",
        "white": "#a9b1d6",
        "brightBlack": "#414868",
        "brightRed": "#f7768e",
        "brightGreen": "#9ece6a",
        "brightYellow": "#e0af68",
        "brightBlue": "#7aa2f7",
        "brightMagenta": "#bb9af7",
        "brightCyan": "#7dcfff",
        "brightWhite": "#c0caf5",
    },
    "catppuccin-mocha": {
        "name": "Catppuccin Mocha",
        "author": "Catppuccin",
        "background": "#1e1e2e",
        "foreground": "#cdd6f4",
        "cursor": "#f5e0dc",
        "selection": "#585b70",
        "black": "#45475a",
        "red": "#f38ba8",
        "green": "#a6e3a1",
        "yellow": "#f9e2af",
        "blue": "#89b4fa",
        "magenta": "#f5c2e7",
        "cyan": "#94e2d5",
        "white": "#bac2de",
        "brightBlack": "#585b70",
        "brightRed": "#f38ba8",
        "brightGreen": "#a6e3a1",
        "brightYellow": "#f9e2af",
        "brightBlue": "#89b4fa",
        "brightMagenta": "#f5c2e7",
        "brightCyan": "#94e2d5",
        "brightWhite": "#a6adc8",
    },
    "catppuccin-latte": {
        "name": "Catppuccin Latte",
        "author": "Catppuccin",
        "background": "#eff1f5",
        "foreground": "#4c4f69",
        "cursor": "#dc8a78",
        "selection": "#acb0be",
        "black": "#5c5f77",
        "red": "#d20f39",
        "green": "#40a02b",
        "yellow": "#df8e1d",
        "blue": "#1e66f5",
        "magenta": "#ea76cb",
        "cyan": "#179299",
        "white": "#acb0be",
        "brightBlack": "#6c6f85",
        "brightRed": "#d20f39",
        "brightGreen": "#40a02b",
        "brightYellow": "#df8e1d",
        "brightBlue": "#1e66f5",
        "brightMagenta": "#ea76cb",
        "brightCyan": "#179299",
        "brightWhite": "#bcc0cc",
    },
    "dracula": {
        "name": "Dracula",
        "author": "Zeno Rocha",
        "background": "#282a36",
        "foreground": "#f8f8f2",
        "cursor": "#f8f8f2",
        "selection": "#44475a",
        "black": "#21222c",
        "red": "#ff5555",
        "green": "#50fa7b",
        "yellow": "#f1fa8c",
        "blue": "#bd93f9",
        "magenta": "#ff79c6",
        "cyan": "#8be9fd",
        "white": "#f8f8f2",
        "brightBlack": "#6272a4",
        "brightRed": "#ff6e6e",
        "brightGreen": "#69ff94",
        "brightYellow": "#ffffa5",
        "brightBlue": "#d6acff",
        "brightMagenta": "#ff92df",
        "brightCyan": "#a4ffff",
        "brightWhite": "#ffffff",
    },
    "nord": {
        "name": "Nord",
        "author": "Arctic Ice Studio",
        "background": "#2e3440",
        "foreground": "#d8dee9",
        "cursor": "#d8dee9",
        "selection": "#434c5e",
        "black": "#3b4252",
        "red": "#bf616a",
        "green": "#a3be8c",
        "yellow": "#ebcb8b",
        "blue": "#81a1c1",
        "magenta": "#b48ead",
        "cyan": "#88c0d0",
        "white": "#e5e9f0",
        "brightBlack": "#4c566a",
        "brightRed": "#bf616a",
        "brightGreen": "#a3be8c",
        "brightYellow": "#ebcb8b",
        "brightBlue": "#81a1c1",
        "brightMagenta": "#b48ead",
        "brightCyan": "#8fbcbb",
        "brightWhite": "#eceff4",
    },
    "gruvbox-dark": {
        "name": "Gruvbox Dark",
        "author": "morhetz",
        "background": "#282828",
        "foreground": "#ebdbb2",
        "cursor": "#ebdbb2",
        "selection": "#504945",
        "black": "#282828",
        "red": "#cc241d",
        "green": "#98971a",
        "yellow": "#d79921",
        "blue": "#458588",
        "magenta": "#b16286",
        "cyan": "#689d6a",
        "white": "#a89984",
        "brightBlack": "#928374",
        "brightRed": "#fb4934",
        "brightGreen": "#b8bb26",
        "brightYellow": "#fabd2f",
        "brightBlue": "#83a598",
        "brightMagenta": "#d3869b",
        "brightCyan": "#8ec07c",
        "brightWhite": "#ebdbb2",
    },
    "cyberpunk": {
        "name": "Cyberpunk Neon",
        "author": "TermCraft",
        "background": "#0d0e15",
        "foreground": "#00ffcc",
        "cursor": "#ff007f",
        "selection": "#2d1637",
        "black": "#10111a",
        "red": "#ff0055",
        "green": "#00ff66",
        "yellow": "#ffe600",
        "blue": "#00e5ff",
        "magenta": "#ff00aa",
        "cyan": "#00f0ff",
        "white": "#e0e6ed",
        "brightBlack": "#3d3f58",
        "brightRed": "#ff3377",
        "brightGreen": "#33ff88",
        "brightYellow": "#fff033",
        "brightBlue": "#33eeff",
        "brightMagenta": "#ff33bb",
        "brightCyan": "#33f5ff",
        "brightWhite": "#ffffff",
    },
    "rose-pine": {
        "name": "Rosé Pine",
        "author": "Rose Pine",
        "background": "#191724",
        "foreground": "#e0def4",
        "cursor": "#524f67",
        "selection": "#2a283e",
        "black": "#26233a",
        "red": "#eb6f92",
        "green": "#31748f",
        "yellow": "#f6c177",
        "blue": "#9ccfd8",
        "magenta": "#c4a7e7",
        "cyan": "#ebbcba",
        "white": "#e0def4",
        "brightBlack": "#6e6a86",
        "brightRed": "#eb6f92",
        "brightGreen": "#31748f",
        "brightYellow": "#f6c177",
        "brightBlue": "#9ccfd8",
        "brightMagenta": "#c4a7e7",
        "brightCyan": "#ebbcba",
        "brightWhite": "#e0def4",
    },
    "synthwave-84": {
        "name": "Synthwave '84",
        "author": "Robb Owen",
        "background": "#262335",
        "foreground": "#ff7edb",
        "cursor": "#fe4450",
        "selection": "#493b5a",
        "black": "#1e1c2b",
        "red": "#fe4450",
        "green": "#72f1b8",
        "yellow": "#fede5d",
        "blue": "#03edf9",
        "magenta": "#ff7edb",
        "cyan": "#03edf9",
        "white": "#f92aad",
        "brightBlack": "#614d85",
        "brightRed": "#fe4450",
        "brightGreen": "#72f1b8",
        "brightYellow": "#fede5d",
        "brightBlue": "#03edf9",
        "brightMagenta": "#ff7edb",
        "brightCyan": "#03edf9",
        "brightWhite": "#ffffff",
    },
    "one-dark": {
        "name": "One Dark Pro",
        "author": "Atom",
        "background": "#282c34",
        "foreground": "#abb2bf",
        "cursor": "#528bff",
        "selection": "#3e4451",
        "black": "#1e2127",
        "red": "#e06c75",
        "green": "#98c379",
        "yellow": "#d19a66",
        "blue": "#61afef",
        "magenta": "#c678dd",
        "cyan": "#56b6c2",
        "white": "#abb2bf",
        "brightBlack": "#5c6370",
        "brightRed": "#e06c75",
        "brightGreen": "#98c379",
        "brightYellow": "#d19a66",
        "brightBlue": "#61afef",
        "brightMagenta": "#c678dd",
        "brightCyan": "#56b6c2",
        "brightWhite": "#ffffff",
    },
    "monokai-pro": {
        "name": "Monokai Pro",
        "author": "Monokai",
        "background": "#2d2a2e",
        "foreground": "#fcfcfa",
        "cursor": "#fcfcfa",
        "selection": "#403e41",
        "black": "#221f22",
        "red": "#ff6188",
        "green": "#a9dc76",
        "yellow": "#ffd866",
        "blue": "#fc9867",
        "magenta": "#ab9df2",
        "cyan": "#78dce8",
        "white": "#fcfcfa",
        "brightBlack": "#727072",
        "brightRed": "#ff6188",
        "brightGreen": "#a9dc76",
        "brightYellow": "#ffd866",
        "brightBlue": "#fc9867",
        "brightMagenta": "#ab9df2",
        "brightCyan": "#78dce8",
        "brightWhite": "#ffffff",
    },
    "kanagawa": {
        "name": "Kanagawa Wave",
        "author": "rebelot",
        "background": "#1f1f28",
        "foreground": "#dcd7ba",
        "cursor": "#c8c093",
        "selection": "#2d4f67",
        "black": "#090618",
        "red": "#c34043",
        "green": "#76946a",
        "yellow": "#c0a36e",
        "blue": "#7e9cd8",
        "magenta": "#957fb8",
        "cyan": "#6a9589",
        "white": "#c8c093",
        "brightBlack": "#727169",
        "brightRed": "#e82424",
        "brightGreen": "#98bb6c",
        "brightYellow": "#e6c384",
        "brightBlue": "#7fb4ca",
        "brightMagenta": "#938aa9",
        "brightCyan": "#7aa89f",
        "brightWhite": "#dcd7ba",
    },
    "everforest": {
        "name": "Everforest Dark",
        "author": "sainnhe",
        "background": "#2d353b",
        "foreground": "#d3c6aa",
        "cursor": "#d3c6aa",
        "selection": "#475258",
        "black": "#343f44",
        "red": "#e67e80",
        "green": "#a7c080",
        "yellow": "#dbbc7f",
        "blue": "#7fbbb3",
        "magenta": "#d699b6",
        "cyan": "#83c092",
        "white": "#d3c6aa",
        "brightBlack": "#475258",
        "brightRed": "#e67e80",
        "brightGreen": "#a7c080",
        "brightYellow": "#dbbc7f",
        "brightBlue": "#7fbbb3",
        "brightMagenta": "#d699b6",
        "brightCyan": "#83c092",
        "brightWhite": "#d3c6aa",
    },
    "night-owl": {
        "name": "Night Owl",
        "author": "Sarah Drasner",
        "background": "#011627",
        "foreground": "#d6deeb",
        "cursor": "#7e57c2",
        "selection": "#1d3b53",
        "black": "#011627",
        "red": "#ef5350",
        "green": "#22da6e",
        "yellow": "#addb67",
        "blue": "#82aaff",
        "magenta": "#c792ea",
        "cyan": "#21c7a8",
        "white": "#ffffff",
        "brightBlack": "#575656",
        "brightRed": "#ef5350",
        "brightGreen": "#22da6e",
        "brightYellow": "#ffeb95",
        "brightBlue": "#82aaff",
        "brightMagenta": "#c792ea",
        "brightCyan": "#7fdbca",
        "brightWhite": "#ffffff",
    },
    "solarized-dark": {
        "name": "Solarized Dark",
        "author": "Ethan Schoonover",
        "background": "#002b36",
        "foreground": "#839496",
        "cursor": "#839496",
        "selection": "#073642",
        "black": "#073642",
        "red": "#dc322f",
        "green": "#859900",
        "yellow": "#b58900",
        "blue": "#268bd2",
        "magenta": "#d33682",
        "cyan": "#2aa198",
        "white": "#eee8d5",
        "brightBlack": "#002b36",
        "brightRed": "#cb4b16",
        "brightGreen": "#586e75",
        "brightYellow": "#657b83",
        "brightBlue": "#839496",
        "brightMagenta": "#6c71c4",
        "brightCyan": "#93a1a1",
        "brightWhite": "#fdf6e3",
    },
    # TODO: bu tema cyber-gradient ile birebir ayni (adi bile ayni: Cyber Neon Gradient).
    # ustelik gradient onizleme/palet listelerinde adi gecmedigi icin gradient
    # ozelliklerinden de faydalanamiyor. ya silinmeli ya kendine ait renkleri olmali
    "rival-gradient": {
        "name": "Rival Magenta Gradient",
        "author": "Rival Development",
        "is_gradient": True,
        "gradient_stops": ["#ff2d95", "#ff5fa2", "#c04dff", "#7b5cff", "#3ba9ff", "#28e0d4"],
        "background": "#0b0713",
        "foreground": "#f5d0ff",
        "cursor": "#ff2d95",
        "selection": "#2a0f3d",
        "black": "#140d1f",
        "red": "#ff2d95",
        "green": "#28e0d4",
        "yellow": "#ffb02e",
        "blue": "#3ba9ff",
        "magenta": "#c04dff",
        "cyan": "#7b5cff",
        "white": "#f5d0ff",
        "brightBlack": "#4a3560",
        "brightRed": "#ff5fa2",
        "brightGreen": "#5cf0e6",
        "brightYellow": "#ffc75f",
        "brightBlue": "#6dc2ff",
        "brightMagenta": "#d47bff",
        "brightCyan": "#9d85ff",
        "brightWhite": "#ffffff",
    }
}

# temalarimizi bat'in kendi tema adlarina esliyoruz. tam karsiligi olmayanlar
# icin gozle en yakin duran temayi sectik. burasi tek kaynak -> sync.py ve
# theme_engine ikisi de buradan okuyor
BAT_THEME_MAP: Dict[str, str] = {
    "cyber-gradient": "tokyonight_night",
    "sunset-gradient": "OneHalfDark",
    "matrix-gradient": "gruvbox-dark",
    "aurora-gradient": "Nord",
    "synthwave-gradient": "Dracula",
    "fire-ice-gradient": "OneHalfDark",
    "deep-space-gradient": "tokyonight_night",
    "rival-gradient": "Dracula",
    "tokyo-night": "tokyonight_night",
    "catppuccin-mocha": "Catppuccin Mocha",
    "catppuccin-latte": "Catppuccin Latte",
    "dracula": "Dracula",
    "nord": "Nord",
    "gruvbox-dark": "gruvbox-dark",
    "cyberpunk": "Dracula",
    "rose-pine": "Catppuccin Mocha",
    "synthwave-84": "Dracula",
    "one-dark": "OneHalfDark",
    "monokai-pro": "Monokai Extended",
    "kanagawa": "gruvbox-dark",
    "everforest": "gruvbox-dark",
    "night-owl": "tokyonight_night",
    "solarized-dark": "Solarized (dark)",
}

# gradient onizlemesi icin kendi renk duraklarini kullanan tema anahtarlari
GRADIENT_THEME_KEYS = tuple(k for k, v in BUILTIN_THEMES.items() if v.get("is_gradient"))

def resolve_theme_key(name: str) -> str:
    """Kullanicinin yazdigi ismi gercek tema anahtarina cevirir.

    "Tokyo Night" -> "tokyo-night". Eslesme yoksa girdiyi oldugu gibi dondurur,
    cagiran taraf bulunamadi hatasini kendisi versin.
    """
    if name in BUILTIN_THEMES:
        return name
    normalized = name.lower().strip().replace(" ", "-").replace("_", "-")
    if normalized in BUILTIN_THEMES:
        return normalized
    return name

def get_bat_theme(theme_name: str) -> str:
    return BAT_THEME_MAP.get(resolve_theme_key(theme_name), "ansi")

def build_fzf_opts(theme: Dict[str, Any]) -> str:
    """Tema renklerinden FZF_DEFAULT_OPTS degerini uretir."""
    bg = theme.get("background", "#08090f")
    fg = theme.get("foreground", "#00ffff")
    hl = theme.get("red", "#ff0055")
    info = theme.get("yellow", "#ffcc00")
    prompt = theme.get("green", "#00ff99")
    pointer = theme.get("magenta", "#a800ff")
    marker = theme.get("cyan", "#00ffff")
    return (
        f"--color=bg+:{bg},bg:{bg},spinner:{marker},hl:{hl} "
        f"--color=fg:{fg},header:{hl},info:{info},pointer:{pointer} "
        f"--color=marker:{marker},fg+:{fg},prompt:{prompt},hl+:{hl}"
    )
